### ISSUE TITLE
I lost the write permission, lol.

### ISSUE THREAD

**Issue by h404bi** [scoopinstaller/install#1]
@r15ch13 Just transfered the repo to `scoopinstaller`.

**Comment by h404bi** [comment]
nevermind, I'll recreate a new repo and delete this one.

**Comment by h404bi** [comment]
@lukesampson can you give a help?

**Comment by lukesampson** [comment]
I gave you admin permissions on this repo so you should be able to delete it now. It looks like GitHub protects repos so that only the organisation owner can delete them by default.

**Comment by h404bi** [comment]
Thanks luke.
