### ISSUE TITLE
Installer doesn't set environment variable SCOOP as ScoopDir

### ISSUE THREAD

**Issue by linsui** [ScoopInstaller/Install#12]
```
PS D:\> .\install.ps1 -ScoopDir 'D:\test'
Downloading...
Extracting...
Creating shim...
Adding D:\test\shims to your path.
Get-ChildItem : 找不到路径“C:\Users\xxx\scoop\shims”，因为该路径不存在。
所在位置 D:\test\apps\scoop\current\lib\commands.ps1:3 字符: 12
+         + (Get-ChildItem "$scoopdir\shims") `
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\xxx\scoop\shims:String
   ) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetCh
   ildItemCommand
```

**Comment by h404bi** [comment]
Please try #13

**Comment by linsui** [comment]
Could you tell me how to test it? :joy: I downloaded the new script and tried to run it but failed because it is not signed. I changed policy to bypass and get "ps requires remotesigned to install scoop".

**Comment by h404bi** [comment]
You need to change the policy to remotesigned: `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser`. https://github.com/ScoopInstaller/Install#prerequisites

**Comment by linsui** [comment]
Failed because it is not signed...

**Comment by h404bi** [comment]
How about entering `A` when it asks for the answer.

**Comment by linsui** [comment]
Still not work and got the same error...

**Comment by h404bi** [comment]
I have no idea about the policy issue you're encountering...
```
Desktop Install (master *)
$ Get-ExecutionPolicy
RemoteSigned
Desktop Install (master *)
$ .\install.ps1 -ScoopDir "D:\test"
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.
Abort.
```

**Comment by linsui** [comment]
It works well :joy: I found if I download it from browser it can't work but if I download it in powershell it works well.

**Comment by h404bi** [comment]
So does the fix work for you?

**Comment by linsui** [comment]
Yeah, it works for me, thanks!
