### ISSUE TITLE
Add-Member : Cannot bind argument to parameter 'InputObject' because it is null.

### ISSUE THREAD

**Issue by r15ch13** [ScoopInstaller/Install#17]
#16 has introduced a new problem with: https://github.com/ScoopInstaller/Install/blob/14079ad991fd5c050a8a1547392cdb871fbe0539/install.ps1#L344

Both checks return `false` and we get:
```diff
PS C:\Users\appveyor> .\install.ps1 -RunAsAdmin
Initializing...
Downloading...
Extracting...
Creating shim...
- Add-Member : Cannot bind argument to parameter 'InputObject' because it is null.
- At C:\Users\appveyor\install.ps1:357 char:28
- + ... oopConfig | Add-Member -MemberType NoteProperty -Name $Name -Value $V ...
- +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-     + CategoryInfo          : InvalidData: (:) [Add-Member], - ParameterBindingValidationException
-     + FullyQualifiedErrorId : - ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.AddMemberCommand
```

![image](https://user-images.githubusercontent.com/432127/75117594-26c69e00-5673-11ea-85e6-31e03596c8ae.png)

**Comment by r15ch13** [comment]
It's now an array containing one element of `$null`
![image](https://user-images.githubusercontent.com/432127/75117714-43170a80-5674-11ea-83f1-a117fddce8c3.png)

**Comment by h404bi** [comment]
Maybe we should apply the fix to line 328:
```powershell
return @(Get-Content $SCOOP_CONFIG_FILE -Raw | ConvertFrom-Json -ErrorAction Stop)
```

instead of line 342:
```powershell
$scoopConfig = @(Use-Config)
```

@r15ch13 can you test it? /cc @MarkMichaelis

**Comment by r15ch13** [comment]
I can't even reproduce the error from #15. The code used in Core is still the same and works.

https://github.com/lukesampson/scoop/blob/a9fa775d59b14e7dce335313faa0eff855469764/lib/core.ps1#L38-L48

What I find strange, is the error message @MarkMichaelis posted was caused by [line 404](https://github.com/ScoopInstaller/Install/blob/14079ad991fd5c050a8a1547392cdb871fbe0539/install.ps1#L404)

**Comment by h404bi** [comment]
> I can't even reproduce the error from #15. The code used in Core is still the same and works.

Have you tweaked `Set-StrictMode -Version Latest`? Set strict mode and the error will occur.

**Comment by r15ch13** [comment]
Okay, that was not mentioned :grin:

**Comment by h404bi** [comment]
```powershell
Set-StrictMode -Version Latest

# powershell 5
("{}" | ConvertFrom-Json -ErrorAction Stop).Count
# The property 'Count' cannot be found on this object. Verify that the property exists.
# At line:1 char:1
# + ("{}" | ConvertFrom-Json -ErrorAction Stop).Count
# + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#     + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
#     + FullyQualifiedErrorId : PropertyNotFoundStrict


# powershell 6+
("{}" | ConvertFrom-Json -ErrorAction Stop).Count
# 1
```

**Comment by r15ch13** [comment]
I guess `.Count` makes no sense here anyway because it will always return 1.

![image](https://user-images.githubusercontent.com/432127/75152231-dac63880-5708-11ea-8307-3304f4fa7c95.png)

**Comment by h404bi** [comment]
Disabling StrictMode is the default setting in PowerShell and it's easier for developers to do scripting development, however, some users have StrictMode enabled in their computers.

I think we should force StrictMode to a value in the installer script.

**Comment by r15ch13** [comment]
I guess we could change the check to
```pwsh
if ($scoopConfig -isnot [System.Management.Automation.PSObject]) { 
```

**Comment by h404bi** [comment]
A special case, assuming the content of config.json is `[1,2]`:
```powershell
("[1,2]" | ConvertFrom-Json) -isnot [System.Management.Automation.PSObject]
# True in PowerShell 6+

("[1,2]" | ConvertFrom-Json) -isnot [System.Management.Automation.PSObject]
# False in PowerShell 5. Damn it! This will escape the if condition flow
$scoopConfig = ("[1,2]" | ConvertFrom-Json)
$scoopConfig | Add-Member -MemberType NoteProperty -Name "debug" -Value "true"
$scoopConfig | ConvertTo-Json
#[
#    {
#        "value":  1,
#        "debug":  "true"
#    },
#    {
#        "value":  2,
#        "debug":  "true"
#    }
#]
# <---- causing unexpected behavior. 😄
```

Although I don't think any user would like to edit and save config.json with array(`[1,2]`).
