### ISSUE TITLE
Cannot install Scoop

### ISSUE THREAD

**Issue by VideoCarp** [ScoopInstaller/Install#24]
#### Current Behavior

Installation fails when instructions are followed exactly. It says the `D` drive is not found.
```
New-Item : Cannot find drive. A drive with the name 'D' does not exist.
At line:483 char:9
+         New-Item -Type Directory $SCOOP_APP_DIR | Out-Null
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (D:String) [New-Item], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.NewItemCommand
```
#### Expected Behavior

A normal installation when Scoop's installation guidelines are followed exactly.
#### Additional context/output

It has broken my VSCode while installing it. And on top of that, it fails to install.

### System details

**Windows version:** [e.g. 7, 8, 10] 10

**OS architecture:** [e.g. 32bit, 64bit] 64bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1645    
```

**Additional software:** [(optional) e.g. ConEmu, Git] Git, Chocolatey, mysys2, vscode, .NET 6.0

#### Scoop Configuration

Not installed.
```json
// N/A
```

**Comment by chawyehsu** [comment]
What's the full installation command you've used?

**Comment by VideoCarp** [comment]
> What's the full installation command you've used?

```powershell
Set-ExecutionPolicy RemoteSigned -Scope CurrentUser # Optional: Needed to run a remote script the first time
Invoke-WebRequest get.scoop.sh -UseBasicParsing | Invoke-Expression
```
This happens no matter the command I use, though. I added `UseBasicParsing` because otherwise it tells me the Internet Explorer engine is not found.

**Comment by chawyehsu** [comment]
I saw it cannot find drive. You did not customize installation directory, then what's the values of environmental variables`$env:SCOOP` and `$env:USERPROFILE` on your machine?

**Comment by VideoCarp** [comment]
`D:\Applications\Scoop` and `C:\Users\Owner` respectively. 

> I saw it cannot find drive. You did not customize installation directory, then what's the values of environment variables `$env:SCOOP` and `$env:USERPROFILE` on your machine?

**Comment by chawyehsu** [comment]
You should not have the `$env:SCOOP` configured if you just used the typical installation command. Could use please remove the environment variable and try again? Please double check if `$env:SCOOP_GLOBAL` and `$env:SCOOP_CACHE` were created and delete them if they exist to make sure you are doing a typical installation.

**Comment by VideoCarp** [comment]
> You should not have the `$env:SCOOP` configured if you just used the typical installation command. Could use please remove the environment variable `$env:SCOOP` and try again? Please double check if `$env:SCOOP_GLOBAL` and `$env:SCOOP_CACHE` were created and delete them if they exist to make sure you are doing a typical installation.

I deleted `$env:SCOOP`. `$env:SCOOP_GLOBAL`, `$env:SCOOP_CACHE` and `$env:SCOOP` all return nothing, now.

**Comment by chawyehsu** [comment]
So does the installation work after deleting those envs?

**Comment by VideoCarp** [comment]
> So does the installation work after deleting those envs?

Yes, thanks
