### ISSUE TITLE
Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by devlman127** [ScoopInstaller/Install#27]
#### Description
I'm really new to this, so sorry if it's a simple fix, but whenever I paste "irm get.scoop.sh | iex" into the powershell line it fails with the following powershell text.
##### PowerShell Context
irm : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:1
\+ irm get.scoop.sh | iex
\+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
#### Additional Information
Windows 10 with BitDefender Free AV

**Comment by ErebosGR** [comment]
Run this first:
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`
Don't close the Powershell window and try the installation command then.

**Comment by devlman127** [comment]
Thanks, it says that Scoop was installed successfully!

**Comment by abakum** [comment]
like chocolatey.org:
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh/install.ps1'))
```
