### ISSUE TITLE
Can't install scoop

### ISSUE THREAD

**Issue by VanTuz5** [ScoopInstaller/Install#29]
![image](https://user-images.githubusercontent.com/39066280/179425332-baee5dcd-dea3-4dd3-953b-fef3cb223c7d.png)

**Comment by Calinou** [comment]
Use a PowerShell prompt as a regular user, not as an administrator.

**Comment by VanTuz5** [comment]
Did not help. Still running as administrator.

**Comment by VanTuz5** [comment]
I installed it manually, after downloading, downloading the ps1 file
