### ISSUE TITLE
Scoop isn't recognized when installed

### ISSUE THREAD

**Issue by FrostyNick** [ScoopInstaller/Install#45]
#### Description

Scoop isn't recognized when installed with the same instructions on the [website](https://scoop.sh/). I tried it a second time which is shown in the screenshot below.

#### Installation Logs and Powershell Context

Second attempt:
![image](https://user-images.githubusercontent.com/57016218/222534937-ed82c704-9d81-481e-b968-094c6660b3d2.png)
Third attempt with verbose logging:
![image](https://user-images.githubusercontent.com/57016218/222535886-225fa629-63f8-4f31-972f-89918c0e0812.png)

#### Additional Information

About:
Edition	Windows 10 Home
Version	21H2
Installed on	‎8/‎13/‎2021
OS build	19044.2486
Experience	Windows Feature Experience Pack 120.2212.4190.0

**Comment by rashil2000** [comment]
Discussed in #46
