### ISSUE TITLE
Scoop installed but command doesn't work "scoop: The term 'scoop' is not recognized..."

### ISSUE THREAD

**Issue by nsde** [ScoopInstaller/Install#46]
#### Description
Possibly a duplicate of #45 

#### Installation Logs
![image](https://user-images.githubusercontent.com/67185896/222968344-1d50f760-2dad-4d4a-8fb7-2a1537ccc7c2.png)

##### PowerShell Context
Name | Value
--- | ---
PSVersion | 7.3.0-rc.1
PSEdition | Core
GitCommitId | 7.3.0-rc.1
OS | Microsoft Windows 10.0.19045
Platform | Win32NT
PSCompatibleVersions | {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion | 2.3
SerializationVersion | 1.1.0.1
WSManStackVersion | 3.0

**Comment by nsde** [comment]
Also tried it with the "normal" PowerShell, and Command Prompt... No luck :/

**Comment by chawyehsu** [comment]
Hello @nsde , what's the value of `$env:PATH` after the installation?

**Comment by nsde** [comment]
> Hello @nsde , what's the value of `$env:PATH` after the installation?

![image](https://user-images.githubusercontent.com/67185896/222970200-3e748f61-4338-44c9-99bf-63f23e973de3.png)

**Comment by nsde** [comment]
There doesn't seem to be any scoop installation

**Comment by chawyehsu** [comment]
That's weird, there should be shim dir path. I'm not sure if the well-known PATH length limit causes this since your PATH contains so many items. May I ask you to check if you can manually append scoop shim path, which should be `C:\Users\<username>\scoop\shims` to the PATH env var from the Environment Variables control panel?

**Comment by nsde** [comment]
Thanks! Now it works. 
I saw that the Python installer had a “Disable path length limit” feature. I think I'd be really nice to have this feature here as well. :)

**Comment by r15ch13** [comment]
You could also split your PATH by copying your manually set directories to new variables and add them.
PATH could like this: `%FIRSTSTUFF%;C:\Windows;C:\Windows\System32;etc...;%MYPATHSTUFF%;%OTHERPROGRAMS%`
