### ISSUE TITLE
Cannot change 'Path' in registry

### ISSUE THREAD

**Issue by jack460** [ScoopInstaller/Install#48]
Hi @WHYBBE & @rashil2000 ,
After https://github.com/ScoopInstaller/Install/pull/44 , we cannot install scoop successfully via Azure Run command (https://learn.microsoft.com/en-us/azure/virtual-machines/windows/run-command).
The root cause is Write-Env does not effect via Azure Run command.
I try to output '$EnvRegisterKey.GetValue($name)' after SetValue, the value is changed. But when I open Registry Editor, I found it remains the original value.
I try to run Write-Env directly inside VM, it works.

**Comment by r15ch13** [comment]
Can you provide a short explanation for setting up a test environment on Azure?

**Comment by jack460** [comment]
> Can you provide a short explanation for setting up a test environment on Azure?

1. Provision an Azure VM
2. At left panel, open 'Run Command' under 'Operations' section.
3. Select 'RunPowerShellScript', execute
`Invoke-Expression "& {$(Invoke-RestMethod get.scoop.sh)} -RunAsAdmin"`
4. Close 'RunPowerShellScript' and reopen, execute `scoop --version`, 'scoop' command is unavailable.

---
In fact, it is caused by `'$EnvRegisterKey.SetValue($name)'` does not affect.

> When we execute:
> `Invoke-Expression "& {$(Invoke-RestMethod get.scoop.sh)} -RunAsAdmin"`
> `scoop --version`
> in the same session, it's OK since they are in the same session, the `$env:PATH = "$SCOOP_SHIMS_DIR;$env:PATH"` in `Add-ShimsDirToPath` affects.

> After we execute `Invoke-Expression "& {$(Invoke-RestMethod get.scoop.sh)} -RunAsAdmin"`, even simply copy 'Write-Env' to 'RunPowerShellScript' console, the registry value is not changed. That's cause we cannot run scoop command in new sessions.

**Comment by WHYBBE** [comment]
Maybe similar to #45 and #46

**Comment by chawyehsu** [comment]
> The function call is probably not needed

@r15ch13 the native `SendMessageTimeout` function call is required, I just tested before your comment. 😅

refs:
https://stackoverflow.com/questions/6979741/setting-environment-variables-requires-reboot-on-64-bit
https://gist.github.com/alphp/78fffb6d69e5bb863c76bbfc767effda
https://github.com/AzureAD/microsoft-authentication-cli/pull/167/files
https://mnaoumov.wordpress.com/2012/07/24/powershell-add-directory-to-environment-path-variable/
https://www.powershellgallery.com/packages/PSCI/1.0.4/Content/core%5Cutils%5CUpdate-EnvironmentVariables.ps1
https://github.com/nodejs/node/pull/613/files
