### ISSUE TITLE
i cannot install scoop

### ISSUE THREAD

**Issue by Arrayweb22** [ScoopInstaller/Install#51]
#### Description

i cannot install i tryed installing it with non-administrator shell

**Comment by HUMORCE** [comment]
Please fill the issue template

**Comment by felaris** [comment]
> #### Description
> i cannot install i tryed installing it with non-administrator shell
> 
> #### Installation Logs
> ##### PowerShell Context
> #### Additional Information
> #### Possible Solution

Can you please copy the error message you get when you try to install so that we can help you out?

**Comment by lwssen** [comment]
Install scoop report below error, how to solve
![image](https://user-images.githubusercontent.com/45806842/232763970-49fc8edf-4fa7-45f8-b56e-8aa3772833dd.png)

**Comment by HUMORCE** [comment]
I'm not sure if this is caused by GFW, you could use VPN/proxy server to bypass GFW then retry.

If not, related issues: https://github.com/ScoopInstaller/Scoop/issues/2337 https://github.com/ScoopInstaller/Extras/issues/5504

**Comment by Ca11ous** [comment]
> Install scoop report below error, how to solve ![image](https://user-images.githubusercontent.com/45806842/232763970-49fc8edf-4fa7-45f8-b56e-8aa3772833dd.png)

You can solve your problem?

**Comment by xxthunder** [comment]
Another possibility would be to disable ssl verification for git:

`git config --global http.sslVerify false`
