### ISSUE TITLE
-ScoopGlobalDir  didn't work when Runasadmin

### ISSUE THREAD

**Issue by arch3rPro** [ScoopInstaller/Install#53]
#### Description

I use the command to install scoop

```
.\install.ps1 -RunAsAdmin -ScoopDir 'D:\Scoop' -ScoopGlobalDir 'D:\GlobalScoopApps' -NoProxy
```
but the ScoopApps was still installed in D:\Scoop\ ，not in D:\GlobalScoopApps

**Comment by HUMORCE** [comment]
> ScoopApps was still installed in D:\Scoop\

What command did you use to install apps as global?

**Comment by arch3rPro** [comment]
thanks，I used scoop install xxxx -g, it works
