### ISSUE TITLE
Invoke-Expression: Error

### ISSUE THREAD

**Issue by Advik-B** [ScoopInstaller/Install#58]
#### Installation Logs

```
VERBOSE: HTTP/1.1 GET with 0-byte payload
VERBOSE: received 25096-byte response of content type text/plain
VERBOSE: Content encoding: utf-8
VERBOSE: -------- PSBoundParameters --------
VERBOSE: [RunAsAdmin, True]
VERBOSE: -------- Environment Variables --------
VERBOSE: $env:USERPROFILE: C:\Users\Advik
VERBOSE: $env:ProgramData: C:\ProgramData
VERBOSE: $env:SCOOP:
VERBOSE: $env:SCOOP_CACHE:
VERBOSE: $env:SCOOP_GLOBAL:
VERBOSE: -------- Selected Variables --------
VERBOSE: SCOOP_DIR: C:\Users\Advik\scoop
VERBOSE: SCOOP_CACHE_DIR: C:\Users\Advik\scoop\cache
VERBOSE: SCOOP_GLOBAL_DIR: C:\ProgramData\scoop
VERBOSE: SCOOP_CONFIG_HOME: C:\Users\Advik\.config
Initializing...
Downloading ...
VERBOSE: Cloning https://github.com/ScoopInstaller/Scoop.git to C:\Users\Advik\scoop\apps\scoop\current
fatal: destination path 'C:\Users\Advik\scoop\apps\scoop\current' already exists and is not an empty directory.
VERBOSE: Cloning https://github.com/ScoopInstaller/Main.git to C:\Users\Advik\scoop\buckets\main
fatal: destination path 'C:\Users\Advik\scoop\buckets\main' already exists and is not an empty directory.
Creating shim...
Adding ~\scoop\shims to your path.
Invoke-Expression: Exception calling "SetValue" with "3" argument(s): "The type of the value object did not match the specified RegistryValueKind or the object could not be properly converted."
```

##### PowerShell Context

PowerShell 7.3.4

#### Additional Information

OS: Windows
AntiVirus: Kaspersky
![NVIDIA_Share_tiMf3DrNyM](https://github.com/ScoopInstaller/Install/assets/86160411/63da4014-0b3a-4ade-a4ba-a830195c8865)

**Comment by Advik-B** [comment]
I did, but it still did not work

**Comment by xxthunder** [comment]
Mmmh, weird. The installer does not create ~\scoop\apps\scoop nor ~\scoop\buckets\main before cloning.

You could try to delete the whole scoop dir: ~\scoop .

Otherwise #57 should fix this issue, too.

**Comment by Advik-B** [comment]
I did try to delete the whole scoop dirctory  but it still did not work

**Comment by HUMORCE** [comment]
https://github.com/ScoopInstaller/Install#advanced-installation

Download `install.ps1`, print `$RegistryValueKind`.
   https://github.com/ScoopInstaller/Install/blob/9b0e9495f0b3a4e781d4a9bd82b62cc257cf4bb0/install.ps1#L427

**Comment by Advik-B** [comment]
> https://github.com/ScoopInstaller/Install#advanced-installation
> 
> Download `install.ps1`, print `$RegistryValueKind`.
> 
> https://github.com/ScoopInstaller/Install/blob/9b0e9495f0b3a4e781d4a9bd82b62cc257cf4bb0/install.ps1#L427

`ExpandString`

**Comment by Advik-B** [comment]
It suddenly worked now?
I think the programming gods smiled upon us

**Comment by WHYBBE** [comment]
> > https://github.com/ScoopInstaller/Install#advanced-installation
> > Download `install.ps1`, print `$RegistryValueKind`.
> > https://github.com/ScoopInstaller/Install/blob/9b0e9495f0b3a4e781d4a9bd82b62cc257cf4bb0/install.ps1#L427
> 
> `ExpandString`

It looks like the Scoop execution directory already exists in your environment variables.

It seems that as long as the type is inconsistent during installation, an error will be reported. This is indeed a problem, the exception should be handled, if it is determined that it is caused by type inconsistency.

**Comment by Advik-B** [comment]
For some reason, it randomly worked now?
