### ISSUE TITLE
Cannot install Scoop in Constrained language mode

### ISSUE THREAD

**Issue by nicerloop** [ScoopInstaller/Install#98]
#### Description
I cannot re-install Scoop as my work station runs PowerShell in Constrained language mode.

Why is the Language mode checked?

I managed to re-install by editing the install script locally and removing the Test-LanguageMode call https://github.com/ScoopInstaller/Install/blob/ff4eedda58d832b8225d7697510f097ebe8ab071/install.ps1#L682C1-L682C18

#### Installation Logs
Scoop requires PowerShell FullLanguage mode to run, current PowerShell environment is restricted.
Abort.

##### PowerShell Context
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

#### Additional Information
Scoop install used to run successfully before commit https://github.com/ScoopInstaller/Install/commit/a3fa920da3d3ad1951e6c50d1b9714f09e33e729

#### Possible Solution
Either remove the LanguageMode check completely, or add a bypass flag.

**Comment by chawyehsu** [comment]
It is expected that the installation quits when PowerShell is in Constrained mode, because Scoop explictly requires PowerShell to be in FullLanguage mdoe to run. 

> I cannot re-install Scoop as my work station

Are you using Scoop in Constrained mode?

**Comment by nicerloop** [comment]
I use Scoop for many years on multiple work machines, and my current machine is in fact running scoop in constrained language mode, as scoop was installed before the addition of the check.

What language features unavailable in constrained mode are effectively used by scoop ? I do not think I have encountered limitions in my use of scoop in constrained mode. 

Can you point me to the origin problem for adding this check ?

**Comment by chawyehsu** [comment]
You can use `$ExecutionContext.SessionState.LanguageMode` to check the language mode of the session you are running Scoop.

For example, in constrained mode only core types can be used, this is not possible to run Scoop in practice.

```
❯ $ExecutionContext.SessionState.LanguageMode
ConstrainedLanguage

❯ # https://github.com/ScoopInstaller/Scoop/blob/master/lib/core.ps1#L690
❯ $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($PROFILE)
InvalidOperation: Cannot invoke method. Method invocation is supported only on core types in this language mode.

❯ New-Object System.Diagnostics.Process
New-Object: Cannot create type. Only core types are supported in this language mode.

❯ scoop
InvalidOperation: C:\Users\[redacted]\scoop\apps\scoop\current\lib\core.ps1:55
Line |
  55 |      $isNewerNetFramework = ([System.Enum]::GetNames([System.Net.Secur …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot invoke method. Method invocation is supported only on core types in this language mode.
InvalidOperation: C:\Users\[redacted]\scoop\apps\scoop\current\lib\core.ps1:62
Line |
  62 |          [System.Net.ServicePointManager]::SecurityProtocol = 3072
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot set property. Property setting is supported only on core types in this language mode.
InvalidOperation: C:\Users\[redacted]\scoop\apps\scoop\current\lib\core.ps1:623
Line |
 623 |  …      return $ExecutionContext.SessionState.Path.GetUnresolvedProvider …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot invoke method. Method invocation is supported only on core types in this language mode.
Test-Path: C:\Users\[redacted]\scoop\apps\scoop\current\lib\core.ps1:1282
Line |
1282 |      if (Test-Path $configPortablePath) {
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Value cannot be null. (Parameter 'The provided Path argument was null or an empty collection.')
ERROR loading C:\Users\[redacted]\.config\scoop\config.json: Cannot invoke method. Method invocation is supported only on core types in this language mode.
InvalidOperation: C:\Users\[redacted]\scoop\apps\scoop\current\lib\core.ps1:1289
Line |
1289 |  … \..\..", "$([System.Environment]::GetFolderPath('UserProfile'))\scoop …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot invoke method. Method invocation is supported only on core types in this language mode.
InvalidOperation: C:\Users\[redacted]\scoop\apps\scoop\current\lib\core.ps1:623
Line |
 623 |  …      return $ExecutionContext.SessionState.Path.GetUnresolvedProvider …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot invoke method. Method invocation is supported only on core types in this language mode.
InvalidOperation: C:\Users\[redacted]\scoop\apps\scoop\current\lib\core.ps1:1292
Line |
1292 |  … L_PATH), "$([System.Environment]::GetFolderPath('CommonApplicationDat …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot invoke method. Method invocation is supported only on core types in this language mode.
InvalidOperation: C:\Users\[redacted]\scoop\apps\scoop\current\lib\core.ps1:623
Line |
 623 |  …      return $ExecutionContext.SessionState.Path.GetUnresolvedProvider …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot invoke method. Method invocation is supported only on core types in this language mode.
InvalidOperation: C:\Users\[redacted]\scoop\apps\scoop\current\lib\core.ps1:623
Line |
 623 |  …      return $ExecutionContext.SessionState.Path.GetUnresolvedProvider …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot invoke method. Method invocation is supported only on core types in this language mode.
Get-ChildItem: C:\Users\[redacted]\scoop\apps\scoop\current\lib\commands.ps1:6
...
```

**Comment by nicerloop** [comment]
Hi, I found a way to work around the limitations. I lifted the constraints imposed by the GPOs.

**Comment by rwijtvliet** [comment]
@nicerloop, can you elaborate? I am in the same situation - I'm on a work PC and unable to start a Powershell session with `FullLanguage` Languagemode due to IT restrictions.

**Comment by rwijtvliet** [comment]
@nicerloop, could you elaborate please? I am in the same situation - I'm on a work PC and unable to start a Powershell session with `FullLanguage` Languagemode due to IT restrictions.

I tried simply commenting out the language check, but the result is not what I wanted

```bash
❯ powershell ./getscoop.ps1
Cannot invoke method. Method invocation is supported only on core types in this language mode.
At C:\Users\rwijtvliet\getscoop.ps1:654 char:5
+     $BoundArgs.GetEnumerator() | ForEach-Object { Write-Verbose $_ }
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MethodInvocationNotSupportedInConstrainedLanguage
```

**Comment by nicerloop** [comment]
Have a look at
- https://github.com/nicerloop/pwsh-noexecpolicy
- https://github.com/nicerloop/homebrew-nicerloop
- https://github.com/nicerloop/setup-docs/blob/main/powershell.md#unrestricted-powershell

**Comment by avy42** [comment]
@rwijtvliet for me running on administrator temporarily allowed me to get FullLanguage Languagemode but then i needed to use different installation. https://github.com/ScoopInstaller/Install?tab=readme-ov-file#for-admin
